# Generated by Django 3.2.6 on 2021-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sending_date', models.DateTimeField(null=True)),
                ('key', models.CharField(max_length=200)),
                ('compensation_key', models.CharField(max_length=255)),
                ('amount', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('awaiting_receipt', 'Awaiting Receipt'), ('received', 'Received'), ('compensated', 'Compensated'), ('sent', 'Sent')], default='awaiting_receipt', max_length=200)),
                ('sending_wallet_account_number', models.CharField(max_length=200)),
                ('receiving_wallet_account_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_key', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('total_scheduled', models.IntegerField(default=0)),
                ('label', models.CharField(choices=[('compensation_sender', 'Compensation Sender'), ('compensation_receiver', 'Compensation Receiver'), ('hybrid_a', 'Hybrid A'), ('hybrid_b', 'Hybrid B')], max_length=50)),
            ],
        ),
    ]
